write_config <- function(
  project_name,
  project_location,
  monitoring_year,
  valid_strata,
  gee_project      = "",
  covariate_raster = "",
  aoi_file         = NULL,
  output_path      = "blue_carbon_config.R"
) {
  strata_str <- paste0('c(', paste0('"', trimws(valid_strata), '"', collapse = ', '), ')')

  palette <- c("#FFFF99", "#99FF99", "#33CC33", "#3399FF", "#FF9999",
               "#CC99FF", "#FFCC99", "#99CCFF", "#FF99CC", "#CCFF99")
  palette <- rep(palette, length.out = length(valid_strata))
  color_entries <- paste(sprintf('  "%s" = "%s"', valid_strata, palette), collapse = ",\n")
  colors_str <- paste0("c(\n", color_entries, "\n)")

  bd_entries <- paste(sprintf('  "%s" = 0.8', valid_strata), collapse = ",\n")
  bd_str <- paste0("list(\n", bd_entries, "\n)")

  gee_line <- if (nchar(trimws(gee_project)) == 0) {
    'GEE_PROJECT <- ""  # Set this before running Pipelines 2, 3, or 4'
  } else {
    paste0('GEE_PROJECT <- "', trimws(gee_project), '"')
  }

  covar_line <- if (nchar(trimws(covariate_raster)) == 0) {
    'COVARIATE_RASTER <- ""  # Set to the path of your GEE covariate raster'
  } else {
    paste0('COVARIATE_RASTER <- "', trimws(covariate_raster), '"')
  }

  aoi_line <- if (is.null(aoi_file) || nchar(trimws(aoi_file)) == 0) {
    'AOI_FILE <- NULL'
  } else {
    paste0('AOI_FILE <- "', trimws(aoi_file), '"')
  }

  lines <- c(
    "# ============================================================================",
    "# BLUE CARBON PROJECT CONFIGURATION",
    paste0("# Generated by the Blue Carbon Setup App on ", Sys.Date()),
    "# ============================================================================",
    "",
    "# ── Project metadata ────────────────────────────────────────────",
    paste0('PROJECT_NAME     <- "', project_name, '"'),
    'PROJECT_SCENARIO <- "PROJECT"   # BASELINE | PROJECT | CONTROL | DEGRADED',
    paste0('MONITORING_YEAR  <- ', as.integer(monitoring_year)),
    paste0('PROJECT_LOCATION <- "', project_location, '"'),
    "",
    "# ── Google Earth Engine ───────────────────────────────────────────",
    gee_line,
    "",
    "# ── Input file paths ─────────────────────────────────────────────",
    'PRE_ANALYSIS_DIR <- "Pre-Analysis Data Preparation"',
    'DATA_RAW_DIR     <- file.path(PRE_ANALYSIS_DIR, "data_raw")',
    'DATA_GLOBAL_DIR  <- file.path(PRE_ANALYSIS_DIR, "data_global")',
    'COVARIATES_DIR   <- file.path(PRE_ANALYSIS_DIR, "covariates")',
    "",
    covar_line,
    "",
    aoi_line,
    "AOI_STRATUM_FIELD <- NULL",
    "",
    "# ── Ecosystem strata ────────────────────────────────────────────",
    paste0("VALID_STRATA <- ", strata_str),
    "",
    paste0("STRATUM_COLORS <- ", colors_str),
    "",
    "# ── VM0033 depth intervals ────────────────────────────────────────",
    "# DO NOT change these values without consulting VM0033 methodology documentation.",
    "VM0033_DEPTH_MIDPOINTS <- c(7.5, 22.5, 40, 75)",
    "",
    "VM0033_DEPTH_INTERVALS <- data.frame(",
    "  depth_top      = c( 0, 15, 30,  50),",
    "  depth_bottom   = c(15, 30, 50, 100),",
    "  depth_midpoint = c(7.5, 22.5, 40, 75),",
    "  thickness_cm   = c(15, 15, 20, 50)",
    ")",
    "",
    "# ── Bulk density defaults ─────────────────────────────────────────",
    "# Applied where bulk_density_g_cm3 is missing in the sample data (g/cm³).",
    paste0("BD_DEFAULTS <- ", bd_str),
    "",
    "# ── QC thresholds ───────────────────────────────────────────────",
    "QC_SOC_MIN <- 0",
    "QC_SOC_MAX <- 500",
    "QC_BD_MIN  <- 0.1",
    "QC_BD_MAX  <- 3.0",
    "",
    "# ── Remote sensing band labels ────────────────────────────────────",
    "BAND_LABELS <- c(",
    '  "SR_B1" = "Coastal aerosol (443 nm) — atmospheric/water",',
    '  "SR_B2" = "Blue (482 nm) — water penetration",',
    '  "SR_B3" = "Green (562 nm) — chlorophyll, turbidity",',
    '  "SR_B4" = "Red (655 nm) — chlorophyll absorption",',
    '  "SR_B5" = "NIR (865 nm) — vegetation biomass ★",',
    '  "SR_B6" = "SWIR-1 (1609 nm) — soil & canopy moisture ★",',
    '  "SR_B7" = "SWIR-2 (2201 nm) — soil organic matter ★",',
    '  "NDVI"  = "NDVI — live green vegetation density ★",',
    '  "EVI"   = "EVI — canopy structure (atmosphere-corrected)",',
    '  "SAVI"  = "SAVI — vegetation with soil-brightness correction",',
    '  "NDWI"  = "NDWI — open water & canopy water content",',
    '  "MNDWI" = "MNDWI — surface water extent",',
    '  "NDMI"  = "NDMI — plant water stress & moisture ★",',
    '  "BSI"   = "BSI — bare soil / unvegetated mudflat",',
    '  "LSWI"  = "LSWI — land surface water index",',
    '  "VV"         = "SAR VV — surface roughness & flooding ★",',
    '  "VH"         = "SAR VH — vegetation structure & biomass ★",',
    '  "VV_VH"      = "SAR VV/VH ratio — vegetation vs. open water",',
    '  "HH"         = "SAR HH — surface scattering",',
    '  "HV"         = "SAR HV — volume scattering / biomass",',
    '  "elevation"  = "Elevation (m) — inundation risk & carbon depth ★",',
    '  "slope"      = "Slope (°) — drainage & sediment transport",',
    '  "aspect"     = "Aspect — solar exposure",',
    '  "TPI"        = "Topographic position index — landform context",',
    '  "TWI"        = "Topographic wetness index — soil moisture",',
    '  "tidal_freq"    = "Tidal inundation frequency — carbon burial rate ★",',
    '  "dist_to_water" = "Distance to water channel (m)",',
    '  "dist_to_coast" = "Distance to coastline (m)",',
    '  "precip"    = "Mean annual precipitation (mm)",',
    '  "temp_mean" = "Mean annual temperature (°C)"',
    ")"
  )

  writeLines(lines, output_path)
  invisible(output_path)
}
